// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'panel-composer-placeholder'
  | 'panel-empty-hint'
  | 'panel-empty-title'
  | 'panel-header'
  | 'panel-not-a-pdf'
  | 'panel-sidenav-tooltip';
