// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'panel-composer-placeholder'
  | 'panel-empty-hint'
  | 'panel-empty-title'
  | 'panel-header'
  | 'panel-not-a-pdf'
  | 'panel-sidenav-tooltip'
  | 'prefs-api-key'
  | 'prefs-api-key-hint'
  | 'prefs-base-url'
  | 'prefs-base-url-hint'
  | 'prefs-connection'
  | 'prefs-font-size'
  | 'prefs-font-size-hint'
  | 'prefs-language'
  | 'prefs-language-hint'
  | 'prefs-lead'
  | 'prefs-model'
  | 'prefs-model-hint'
  | 'prefs-status-checking'
  | 'prefs-status-fail'
  | 'prefs-status-idle'
  | 'prefs-status-ok'
  | 'prefs-test'
  | 'prefs-title';
