// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiBaseUrl": string;
      "apiKey": string;
      "model": string;
      "replyLanguage": string;
      "fontSize": number;
      "followZoteroTheme": boolean;
      "showSelectionPopupButtons": boolean;
      "translateEngine": string;
      "translateDeeplKey": string;
      "translateGoogleCloudKey": string;
      "translateAzureKey": string;
      "translateAzureRegion": string;
      "translateFontSize": number;
      "translatePopupWidth": number;
      "translatePopupHeight": number;
      "showCostBar": boolean;
      "debugDumpPayload": boolean;
      "devSeedPDF": string;
      "devApiKeyFile": string;
      "devShowRadixProbe": boolean;
      "devShowAssistantProbe": boolean;
    };
  }
}
