// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiBaseUrl": string;
      "model": string;
      "followZoteroTheme": boolean;
      "showSelectionPopupButtons": boolean;
      "showCostBar": boolean;
      "debugDumpPayload": boolean;
      "devSeedPDF": string;
    };
  }
}
